#define CONFIG_SPECTRA_CAMERA 1
#define CONFIG_SPECTRA_ISP 1
#define CONFIG_SPECTRA_ICP 1
#define CONFIG_SPECTRA_JPEG 1
#define CONFIG_SPECTRA_FD 1
#define CONFIG_SPECTRA_LRME 1
#define CONFIG_SPECTRA_SENSOR 1
#define CONFIG_USE_BU64748 1
