/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
#ifndef __MSM_VIDC_UTILS_H__
#define __MSM_VIDC_UTILS_H__

#include <linux/types.h>
#include <linux/v4l2-controls.h>

/* SDM845 misr info */
#define VENUS_USES_LEGACY_MISR_INFO

#define MSM_VIDC_HAL_INTERLACE_COLOR_FORMAT_NV12	0x2
#define MSM_VIDC_HAL_INTERLACE_COLOR_FORMAT_NV12_UBWC	0x8002
#define MSM_VIDC_EXTRADATA_FRAME_QP_ADV 0x1

/* RGB formats start */
#define V4L2_PIX_FMT_RGB555  v4l2_fourcc('R', 'G', 'B', 'O') /* 16  RGB-5-5-5     */
#define V4L2_PIX_FMT_ARGB555 v4l2_fourcc('A', 'R', '1', '5') /* 16  ARGB-1-5-5-5  */
#define V4L2_PIX_FMT_XRGB555 v4l2_fourcc('X', 'R', '1', '5') /* 16  XRGB-1-5-5-5  */
#define V4L2_PIX_FMT_RGB565  v4l2_fourcc('R', 'G', 'B', 'P') /* 16  RGB-5-6-5     */
#define V4L2_PIX_FMT_RGB555X v4l2_fourcc('R', 'G', 'B', 'Q') /* 16  RGB-5-5-5 BE  */
#define V4L2_PIX_FMT_ARGB555X v4l2_fourcc_be('A', 'R', '1', '5') /* 16  ARGB-5-5-5 BE */
#define V4L2_PIX_FMT_XRGB555X v4l2_fourcc_be('X', 'R', '1', '5') /* 16  XRGB-5-5-5 BE */
#define V4L2_PIX_FMT_RGB565X v4l2_fourcc('R', 'G', 'B', 'R') /* 16  RGB-5-6-5 BE  */
#define V4L2_PIX_FMT_BGR666  v4l2_fourcc('B', 'G', 'R', 'H') /* 18  BGR-6-6-6	  */
#define V4L2_PIX_FMT_BGR24   v4l2_fourcc('B', 'G', 'R', '3') /* 24  BGR-8-8-8     */
#define V4L2_PIX_FMT_RGB24   v4l2_fourcc('R', 'G', 'B', '3') /* 24  RGB-8-8-8     */
#define V4L2_PIX_FMT_BGR32   v4l2_fourcc('B', 'G', 'R', '4') /* 32  BGR-8-8-8-8   */
#define V4L2_PIX_FMT_ABGR32  v4l2_fourcc('A', 'R', '2', '4') /* 32  BGRA-8-8-8-8  */
#define V4L2_PIX_FMT_XBGR32  v4l2_fourcc('X', 'R', '2', '4') /* 32  BGRX-8-8-8-8  */
#define V4L2_PIX_FMT_RGB32   v4l2_fourcc('R', 'G', 'B', '4') /* 32  RGB-8-8-8-8   */
#define V4L2_PIX_FMT_ARGB32  v4l2_fourcc('B', 'A', '2', '4') /* 32  ARGB-8-8-8-8  */
#define V4L2_PIX_FMT_XRGB32  v4l2_fourcc('B', 'X', '2', '4') /* 32  XRGB-8-8-8-8  */
#define V4L2_PIX_FMT_RGBA8888_UBWC   v4l2_fourcc('Q', 'R', 'G', 'B')
/* RGB formats end */

/* Bayer formats start - see http://www.siliconimaging.com/RGB%20Bayer.htm */
#define V4L2_PIX_FMT_SBGGR10DPCM6 v4l2_fourcc('b', 'B', 'A', '6')
#define V4L2_PIX_FMT_SGBRG10DPCM6 v4l2_fourcc('b', 'G', 'A', '6')
#define V4L2_PIX_FMT_SGRBG10DPCM6 v4l2_fourcc('B', 'D', '1', '6')
#define V4L2_PIX_FMT_SRGGB10DPCM6 v4l2_fourcc('b', 'R', 'A', '6')
#define V4L2_PIX_FMT_SBGGRPLAIN16 v4l2_fourcc('B', 'G', '1', '6')
#define V4L2_PIX_FMT_SGBRGPLAIN16 v4l2_fourcc('G', 'B', '1', '6')
#define V4L2_PIX_FMT_SGRBGPLAIN16 v4l2_fourcc('G', 'R', '1', '6')
#define V4L2_PIX_FMT_SRGGBPLAIN16 v4l2_fourcc('R', 'G', '1', '6')
/* Bayer formats end - see http://www.siliconimaging.com/RGB%20Bayer.htm */

/* compressed formats start */
#define V4L2_PIX_FMT_DIVX_311  v4l2_fourcc('D', 'I', 'V', '3') /* DIVX311     */
#define V4L2_PIX_FMT_DIVX      v4l2_fourcc('D', 'I', 'V', 'X') /* DIVX  */
#define V4L2_PIX_FMT_HEVC_HYBRID v4l2_fourcc('H', 'V', 'C', 'H')
#define V4L2_PIX_FMT_TME      v4l2_fourcc('T', 'M', 'E', '0') /* TME stream */
#define V4L2_PIX_FMT_CVP      v4l2_fourcc('C', 'V', 'P', '0') /* CVP stream */
/* compressed formats end */

/* vendor color format start */
/* NV12_512 8-bit Y/CbCr 4:2:0  */
#define V4L2_PIX_FMT_NV12_512         v4l2_fourcc('Q', '5', '1', '2')
/* UBWC 8-bit Y/CbCr 4:2:0  */
#define V4L2_PIX_FMT_NV12_UBWC        v4l2_fourcc('Q', '1', '2', '8')
/* UBWC 10-bit Y/CbCr 4:2:0 */
#define V4L2_PIX_FMT_NV12_TP10_UBWC   v4l2_fourcc('Q', '1', '2', 'A')
#define V4L2_PIX_FMT_NV12_P010_UBWC   v4l2_fourcc('Q', '1', '2', 'B')
#define V4L2_PIX_FMT_SDE_ABGR_8888 \
	v4l2_fourcc('R', 'A', '2', '4') /* 32-bit ABGR 8:8:8:8 */
#define V4L2_PIX_FMT_SDE_RGBA_8888 \
	v4l2_fourcc('A', 'B', '2', '4') /* 32-bit RGBA 8:8:8:8 */
#define V4L2_PIX_FMT_SDE_RGBX_8888 \
	v4l2_fourcc('X', 'B', '2', '4') /* 32-bit RGBX 8:8:8:8 */
#define V4L2_PIX_FMT_SDE_XBGR_8888 \
	v4l2_fourcc('R', 'X', '2', '4') /* 32-bit XBGR 8:8:8:8 */
#define V4L2_PIX_FMT_SDE_RGBA_5551 \
	v4l2_fourcc('R', 'A', '1', '5') /* 16-bit RGBA 5:5:5:1 */
#define V4L2_PIX_FMT_SDE_ABGR_1555 \
	v4l2_fourcc('A', 'B', '1', '5') /* 16-bit ABGR 1:5:5:5 */
#define V4L2_PIX_FMT_SDE_BGRA_5551 \
	v4l2_fourcc('B', 'A', '1', '5') /* 16-bit BGRA 5:5:5:1 */
#define V4L2_PIX_FMT_SDE_BGRX_5551 \
	v4l2_fourcc('B', 'X', '1', '5') /* 16-bit BGRX 5:5:5:1 */
#define V4L2_PIX_FMT_SDE_RGBX_5551 \
	v4l2_fourcc('R', 'X', '1', '5') /* 16-bit RGBX 5:5:5:1 */
#define V4L2_PIX_FMT_SDE_XBGR_1555 \
	v4l2_fourcc('X', 'B', '1', '5') /* 16-bit XBGR 1:5:5:5 */
#define V4L2_PIX_FMT_SDE_RGBA_4444 \
	v4l2_fourcc('R', 'A', '1', '2') /* 16-bit RGBA 4:4:4:4 */
#define V4L2_PIX_FMT_SDE_BGRA_4444 \
	v4l2_fourcc('b', 'A', '1', '2') /* 16-bit BGRA 4:4:4:4 */
#define V4L2_PIX_FMT_SDE_ABGR_4444 \
	v4l2_fourcc('A', 'B', '1', '2') /* 16-bit ABGR 4:4:4:4 */
#define V4L2_PIX_FMT_SDE_RGBX_4444 \
	v4l2_fourcc('R', 'X', '1', '2') /* 16-bit RGBX 4:4:4:4 */
#define V4L2_PIX_FMT_SDE_BGRX_4444 \
	v4l2_fourcc('B', 'X', '1', '2') /* 16-bit BGRX 4:4:4:4 */
#define V4L2_PIX_FMT_SDE_XBGR_4444 \
	v4l2_fourcc('X', 'B', '1', '2') /* 16-bit XBGR 4:4:4:4 */
#define V4L2_PIX_FMT_SDE_BGR_565 \
	v4l2_fourcc('B', 'G', '1', '6') /* 16-bit BGR 5:6:5 */
#define V4L2_PIX_FMT_SDE_Y_CR_CB_GH2V2 \
	v4l2_fourcc('Y', 'U', '4', '2') /* Planar YVU 4:2:0 A16 */
#define V4L2_PIX_FMT_SDE_Y_CBCR_H1V2 \
	v4l2_fourcc('N', 'H', '1', '6') /* Y/CbCr 4:2:2 */
#define V4L2_PIX_FMT_SDE_Y_CRCB_H1V2 \
	v4l2_fourcc('N', 'H', '6', '1') /* Y/CrCb 4:2:2 */
#define V4L2_PIX_FMT_SDE_Y_CBCR_H2V2_VENUS \
	v4l2_fourcc('Q', 'N', 'V', '2') /* Y/CbCr 4:2:0 Venus */
#define V4L2_PIX_FMT_SDE_Y_CRCB_H2V2_VENUS \
	v4l2_fourcc('Q', 'N', 'V', '1') /* Y/CrCb 4:2:0 Venus */
#define V4L2_PIX_FMT_SDE_RGBX_8888_UBWC \
	v4l2_fourcc('Q', 'X', 'B', '4') /* RGBX 8:8:8:8 UBWC */
#define V4L2_PIX_FMT_SDE_RGB_565_UBWC \
	v4l2_fourcc('Q', 'R', 'G', '6') /* RGB 5:6:5 UBWC */
#define V4L2_PIX_FMT_SDE_RGBA_1010102 \
	v4l2_fourcc('A', 'B', '3', '0') /* RGBA 10:10:10:2 */
#define V4L2_PIX_FMT_SDE_RGBX_1010102 \
	v4l2_fourcc('X', 'B', '3', '0') /* RGBX 10:10:10:2 */
#define V4L2_PIX_FMT_SDE_ARGB_2101010 \
	v4l2_fourcc('A', 'R', '3', '0') /* ARGB 2:10:10:10 */
#define V4L2_PIX_FMT_SDE_XRGB_2101010 \
	v4l2_fourcc('X', 'R', '3', '0') /* XRGB 2:10:10:10 */
#define V4L2_PIX_FMT_SDE_BGRA_1010102 \
	v4l2_fourcc('B', 'A', '3', '0') /* BGRA 10:10:10:2 */
#define V4L2_PIX_FMT_SDE_BGRX_1010102 \
	v4l2_fourcc('B', 'X', '3', '0') /* BGRX 10:10:10:2 */
#define V4L2_PIX_FMT_SDE_ABGR_2101010 \
	v4l2_fourcc('R', 'A', '3', '0') /* ABGR 2:10:10:10 */
#define V4L2_PIX_FMT_SDE_XBGR_2101010 \
	v4l2_fourcc('R', 'X', '3', '0') /* XBGR 2:10:10:10 */
#define V4L2_PIX_FMT_SDE_RGBA_1010102_UBWC \
	v4l2_fourcc('Q', 'R', 'B', 'A') /* RGBA 10:10:10:2 UBWC */
#define V4L2_PIX_FMT_SDE_RGBX_1010102_UBWC \
	v4l2_fourcc('Q', 'X', 'B', 'A') /* RGBX 10:10:10:2 UBWC */
#define V4L2_PIX_FMT_SDE_Y_CBCR_H2V2_TP10 \
	v4l2_fourcc('T', 'P', '1', '0') /* Y/CbCr 4:2:0 TP10 */
#define V4L2_PIX_FMT_SDE_Y_CBCR_H2V2_P010 \
	v4l2_fourcc('P', '0', '1', '0') /* Y/CbCr 4:2:0 P10 */
#define V4L2_PIX_FMT_SDE_Y_CBCR_H2V2_P010_VENUS \
	v4l2_fourcc('Q', 'P', '1', '0') /* Y/CbCr 4:2:0 P10 Venus*/
/* vendor color format end */

/* Vendor extensions start */
#define V4L2_BUF_FLAG_CODECCONFIG		0x00020000
#define V4L2_BUF_FLAG_END_OF_SUBFRAME		0x00000080
#define V4L2_BUF_FLAG_DATA_CORRUPT		0x00400000
#define V4L2_BUF_INPUT_UNSUPPORTED		0x01000000
#define V4L2_BUF_FLAG_EOS			0x02000000
#define V4L2_BUF_FLAG_READONLY		0x04000000
#define V4L2_BUF_FLAG_PERF_MODE		0x20000000
#define V4L2_BUF_FLAG_CVPMETADATA_SKIP		0x40000000
#define V4L2_QCOM_BUF_FLAG_EOSEQ                0x00040000
#define V4L2_QCOM_BUF_TIMESTAMP_INVALID         0x00080000
#define V4L2_MSM_BUF_FLAG_MBAFF                 0x00000200
#define V4L2_QCOM_BUF_FLAG_DECODEONLY           0x00200000
#define V4L2_QCOM_BUF_DROP_FRAME                0x00800000
#define V4L2_MSM_VIDC_BUF_START_CODE_NOT_FOUND  0x08000000
#define V4L2_MSM_BUF_FLAG_YUV_601_709_CLAMP     0x10000000
#define V4L2_MSM_BUF_FLAG_DEFER                 0x40000000
#define V4L2_QCOM_BUF_FLAG_IDRFRAME             0x80000000
#define V4L2_QCOM_BUF_END_OF_SUBFRAME   V4L2_BUF_FLAG_END_OF_SUBFRAME
#define V4L2_QCOM_BUF_FLAG_CODECCONFIG  V4L2_BUF_FLAG_CODECCONFIG
#define V4L2_QCOM_BUF_INPUT_UNSUPPORTED V4L2_BUF_INPUT_UNSUPPORTED
#define V4L2_QCOM_BUF_FLAG_EOS	V4L2_BUF_FLAG_EOS
#define V4L2_QCOM_BUF_FLAG_READONLY V4L2_BUF_FLAG_READONLY
#define V4L2_QCOM_BUF_FLAG_PERF_MODE	V4L2_BUF_FLAG_PERF_MODE
/* Vendor extensions end */

/* Decoder commands start */
#define V4L2_CMD_FLUSH      (4)
#define V4L2_CMD_SESSION_CONTINUE (5)
#define V4L2_DEC_QCOM_CMD_RECONFIG_HINT  (6)
/* Decoder commands end */

/* Flags for V4L2_CMD_FLUSH start */
#define V4L2_CMD_FLUSH_OUTPUT  (1 << 0)
#define V4L2_CMD_FLUSH_CAPTURE (1 << 1)
#define V4L2_QCOM_CMD_FLUSH	V4L2_CMD_FLUSH
#define V4L2_QCOM_CMD_SESSION_CONTINUE	V4L2_CMD_SESSION_CONTINUE
#define V4L2_QCOM_CMD_FLUSH_OUTPUT	V4L2_CMD_FLUSH_OUTPUT
#define V4L2_QCOM_CMD_FLUSH_CAPTURE	V4L2_CMD_FLUSH_CAPTURE
/* Flags for V4L2_CMD_FLUSH end */

/* missing v4l2 entries start */
enum v4l2_mpeg_vidc_video_bitrate_mode {
	V4L2_MPEG_VIDEO_BITRATE_MODE_MBR =
		V4L2_MPEG_VIDEO_BITRATE_MODE_CBR +1,
	/* RC_OFF */
	V4L2_MPEG_VIDEO_BITRATE_MODE_RC_OFF,
	V4L2_MPEG_VIDEO_BITRATE_MODE_CBR_VFR,
	V4L2_MPEG_VIDEO_BITRATE_MODE_MBR_VFR,
	V4L2_MPEG_VIDEO_BITRATE_MODE_CQ,
};
/* missing v4l2 entries end */

/* vendor controls start */
#define V4L2_EVENT_BITDEPTH_FLAG	0x1
#define V4L2_EVENT_PICSTRUCT_FLAG	0x2
#define V4L2_EVENT_COLOUR_SPACE_FLAG	0x4
#define V4L2_EVENT_MSM_VIDC_START	(V4L2_EVENT_PRIVATE_START + 0x00001000)
#define V4L2_EVENT_MSM_VIDC_FLUSH_DONE	(V4L2_EVENT_MSM_VIDC_START + 1)
#define V4L2_EVENT_MSM_VIDC_PORT_SETTINGS_CHANGED_SUFFICIENT	\
		(V4L2_EVENT_MSM_VIDC_START + 2)
#define V4L2_EVENT_MSM_VIDC_PORT_SETTINGS_CHANGED_INSUFFICIENT	\
		(V4L2_EVENT_MSM_VIDC_START + 3)
/*
 * Bitdepth changed insufficient is deprecated now, however retaining
 * to prevent changing the values of the other macros after bitdepth
 */
#define V4L2_EVENT_MSM_VIDC_PORT_SETTINGS_BITDEPTH_CHANGED_INSUFFICIENT \
		(V4L2_EVENT_MSM_VIDC_START + 4)
#define V4L2_EVENT_MSM_VIDC_SYS_ERROR	(V4L2_EVENT_MSM_VIDC_START + 5)
#define V4L2_EVENT_MSM_VIDC_RELEASE_BUFFER_REFERENCE \
		(V4L2_EVENT_MSM_VIDC_START + 6)
#define V4L2_EVENT_MSM_VIDC_RELEASE_UNQUEUED_BUFFER \
		(V4L2_EVENT_MSM_VIDC_START + 7)
#define V4L2_EVENT_MSM_VIDC_HW_OVERLOAD (V4L2_EVENT_MSM_VIDC_START + 8)
#define V4L2_EVENT_MSM_VIDC_MAX_CLIENTS (V4L2_EVENT_MSM_VIDC_START + 9)
#define V4L2_EVENT_MSM_VIDC_HW_UNSUPPORTED (V4L2_EVENT_MSM_VIDC_START + 10)
#define V4L2_EVENT_MSM_VIDC_REGISTER_BUFFER_DONE \
		(V4L2_EVENT_MSM_VIDC_START + 11)
#define V4L2_EVENT_MSM_VIDC_UNREGISTER_BUFFER_DONE \
		(V4L2_EVENT_MSM_VIDC_START + 12)
/*
 *  CVP Events
 */
#define V4L2_EVENT_MSM_CVP_START	(V4L2_EVENT_PRIVATE_START + 0x00001000)
#define V4L2_EVENT_MSM_CVP_FLUSH_DONE	(V4L2_EVENT_MSM_CVP_START + 1)
#define V4L2_EVENT_MSM_CVP_PORT_SETTINGS_CHANGED_SUFFICIENT	\
		(V4L2_EVENT_MSM_CVP_START + 2)
#define V4L2_EVENT_MSM_CVP_PORT_SETTINGS_CHANGED_INSUFFICIENT	\
		(V4L2_EVENT_MSM_CVP_START + 3)

#define V4L2_EVENT_MSM_CVP_SYS_ERROR	(V4L2_EVENT_MSM_CVP_START + 5)
#define V4L2_EVENT_MSM_CVP_RELEASE_BUFFER_REFERENCE \
		(V4L2_EVENT_MSM_CVP_START + 6)
#define V4L2_EVENT_MSM_CVP_RELEASE_UNQUEUED_BUFFER \
		(V4L2_EVENT_MSM_CVP_START + 7)
#define V4L2_EVENT_MSM_CVP_HW_OVERLOAD (V4L2_EVENT_MSM_CVP_START + 8)
#define V4L2_EVENT_MSM_CVP_MAX_CLIENTS (V4L2_EVENT_MSM_CVP_START + 9)
#define V4L2_EVENT_MSM_CVP_HW_UNSUPPORTED (V4L2_EVENT_MSM_CVP_START + 10)
#define V4L2_EVENT_MSM_CVP_REGISTER_BUFFER_DONE \
		(V4L2_EVENT_MSM_CVP_START + 11)
#define V4L2_EVENT_MSM_CVP_UNREGISTER_BUFFER_DONE \
		(V4L2_EVENT_MSM_CVP_START + 12)
/* vendor controls end */


/* (BASE_VIDIOC_PRIVATE + 0) is private ioctl code for video module */
#define BASE_VIDIOC_PRIVATE_VIDEO	(BASE_VIDIOC_PRIVATE + 0)

/* (BASE_VIDIOC_PRIVATE + 1) is private ioctl code for cvp module */
#define BASE_VIDIOC_PRIVATE_CVP	(BASE_VIDIOC_PRIVATE + 1)

/*  MPEG-class control IDs specific to the msm_vidc driver */
#define V4L2_CID_MPEG_MSM_VIDC_BASE		(V4L2_CTRL_CLASS_MPEG | 0x2000)

#define V4L2_MPEG_MSM_VIDC_DISABLE 0
#define V4L2_MPEG_MSM_VIDC_ENABLE 1

#define V4L2_CID_MPEG_VIDC_VIDEO_PICTYPE_DEC_MODE \
			(V4L2_CID_MPEG_MSM_VIDC_BASE+0)
enum v4l2_mpeg_vidc_video_pictype_dec_mode {
	V4L2_MPEG_VIDC_VIDEO_PICTYPE_DECODE_I = 1,
	V4L2_MPEG_VIDC_VIDEO_PICTYPE_DECODE_P = 2,
	V4L2_MPEG_VIDC_VIDEO_PICTYPE_DECODE_B = 4,
};

enum v4l2_mpeg_vidc_video_pictype_dec_enable {
	V4L2_MPEG_VIDC_VIDEO_PICTYPE_DECODE_OFF = 0,
	V4L2_MPEG_VIDC_VIDEO_PICTYPE_DECODE_ON = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_KEEP_ASPECT_RATIO \
	(V4L2_CID_MPEG_MSM_VIDC_BASE+1)

#define V4L2_CID_MPEG_VIDC_VIDEO_STREAM_FORMAT   (V4L2_CID_MPEG_MSM_VIDC_BASE+2)
enum v4l2_mpeg_vidc_video_stream_format {
	V4L2_MPEG_VIDC_VIDEO_NAL_FORMAT_STARTCODES         = 0,
	V4L2_MPEG_VIDC_VIDEO_NAL_FORMAT_ONE_NAL_PER_BUFFER = 1,
	V4L2_MPEG_VIDC_VIDEO_NAL_FORMAT_ONE_BYTE_LENGTH    = 2,
	V4L2_MPEG_VIDC_VIDEO_NAL_FORMAT_TWO_BYTE_LENGTH    = 3,
	V4L2_MPEG_VIDC_VIDEO_NAL_FORMAT_FOUR_BYTE_LENGTH   = 4,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_OUTPUT_ORDER   (V4L2_CID_MPEG_MSM_VIDC_BASE+3)
enum v4l2_mpeg_vidc_video_output_order {
	V4L2_MPEG_VIDC_VIDEO_OUTPUT_ORDER_DISPLAY         = 0,
	V4L2_MPEG_VIDC_VIDEO_OUTPUT_ORDER_DECODE          = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_FRAME_RATE   (V4L2_CID_MPEG_MSM_VIDC_BASE+4)
#define V4L2_CID_MPEG_VIDC_VIDEO_IDR_PERIOD   (V4L2_CID_MPEG_MSM_VIDC_BASE+5)
#define V4L2_CID_MPEG_VIDC_VIDEO_NUM_P_FRAMES (V4L2_CID_MPEG_MSM_VIDC_BASE+6)
#define V4L2_CID_MPEG_VIDC_VIDEO_NUM_B_FRAMES (V4L2_CID_MPEG_MSM_VIDC_BASE+7)
#define V4L2_CID_MPEG_VIDC_VIDEO_REQUEST_IFRAME (V4L2_CID_MPEG_MSM_VIDC_BASE+8)

#define V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL (V4L2_CID_MPEG_MSM_VIDC_BASE+9)
enum v4l2_mpeg_vidc_video_rate_control {
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_OFF = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_VBR_VFR = 1,
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_VBR_CFR = 2,
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_CBR_VFR = 3,
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_CBR_CFR = 4,
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_MBR_CFR = 5,
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_MBR_VFR = 6,
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_CQ = 7,
};
#define V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_MBR_CFR   \
		V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_MBR_CFR
#define V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_MBR_VFR   \
		V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_MBR_VFR

#define V4L2_CID_MPEG_VIDC_VIDEO_ROTATION (V4L2_CID_MPEG_MSM_VIDC_BASE+10)
enum v4l2_mpeg_vidc_video_rotation {
	V4L2_CID_MPEG_VIDC_VIDEO_ROTATION_NONE = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_ROTATION_90 = 1,
	V4L2_CID_MPEG_VIDC_VIDEO_ROTATION_180 = 2,
	V4L2_CID_MPEG_VIDC_VIDEO_ROTATION_270 = 3,
};
#define V4L2_CID_MPEG_VIDC_VIDEO_H264_CABAC_MODEL \
		(V4L2_CID_MPEG_MSM_VIDC_BASE+11)
enum v4l2_mpeg_vidc_h264_cabac_model {
	V4L2_CID_MPEG_VIDC_VIDEO_H264_CABAC_MODEL_0 = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_H264_CABAC_MODEL_1 = 1,
	V4L2_CID_MPEG_VIDC_VIDEO_H264_CABAC_MODEL_2 = 2,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_MODE_CYCLIC \
		(V4L2_CID_MPEG_MSM_VIDC_BASE+12)

#define V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_RANDOM \
		(V4L2_CID_MPEG_MSM_VIDC_BASE+13)
#define V4L2_CID_MPEG_VIDC_VIDEO_AU_DELIMITER \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 14)

enum v4l2_mpeg_vidc_video_au_delimiter {
	V4L2_MPEG_VIDC_VIDEO_AU_DELIMITER_DISABLED = 0,
	V4L2_MPEG_VIDC_VIDEO_AU_DELIMITER_ENABLED = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_SYNC_FRAME_DECODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 15)

enum v4l2_mpeg_vidc_video_sync_frame_decode {
	V4L2_MPEG_VIDC_VIDEO_SYNC_FRAME_DECODE_DISABLE = 0,
	V4L2_MPEG_VIDC_VIDEO_SYNC_FRAME_DECODE_ENABLE = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_SECURE (V4L2_CID_MPEG_MSM_VIDC_BASE+16)
#define V4L2_CID_MPEG_VIDC_VIDEO_EXTRADATA \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 17)
enum v4l2_mpeg_vidc_extradata {
	V4L2_MPEG_VIDC_EXTRADATA_NONE = 0,
	V4L2_MPEG_VIDC_EXTRADATA_MB_QUANTIZATION = 1,
	V4L2_MPEG_VIDC_EXTRADATA_INTERLACE_VIDEO = 2,
#define V4L2_MPEG_VIDC_EXTRADATA_ENC_DTS \
	V4L2_MPEG_VIDC_EXTRADATA_ENC_DTS
	V4L2_MPEG_VIDC_EXTRADATA_ENC_DTS = 3,
	V4L2_MPEG_VIDC_EXTRADATA_VC1_FRAMEDISP = 4,
	V4L2_MPEG_VIDC_EXTRADATA_TIMESTAMP = 5,
	V4L2_MPEG_VIDC_EXTRADATA_S3D_FRAME_PACKING = 6,
	V4L2_MPEG_VIDC_EXTRADATA_FRAME_RATE = 7,
	V4L2_MPEG_VIDC_EXTRADATA_PANSCAN_WINDOW = 8,
	V4L2_MPEG_VIDC_EXTRADATA_RECOVERY_POINT_SEI = 9,
	V4L2_MPEG_VIDC_EXTRADATA_MULTISLICE_INFO = 10,
	V4L2_MPEG_VIDC_EXTRADATA_NUM_CONCEALED_MB = 11,
	V4L2_MPEG_VIDC_EXTRADATA_METADATA_FILLER = 12,
#define V4L2_MPEG_VIDC_EXTRADATA_INPUT_CROP \
	V4L2_MPEG_VIDC_EXTRADATA_INPUT_CROP
	V4L2_MPEG_VIDC_EXTRADATA_INPUT_CROP = 13,
	V4L2_MPEG_VIDC_EXTRADATA_DIGITAL_ZOOM = 14,
	V4L2_MPEG_VIDC_EXTRADATA_ASPECT_RATIO = 15,
	V4L2_MPEG_VIDC_EXTRADATA_MPEG2_SEQDISP = 16,
	V4L2_MPEG_VIDC_EXTRADATA_STREAM_USERDATA = 17,
	V4L2_MPEG_VIDC_EXTRADATA_FRAME_QP = 18,
	V4L2_MPEG_VIDC_EXTRADATA_FRAME_BITS_INFO = 19,
	V4L2_MPEG_VIDC_EXTRADATA_LTR = 20,
	V4L2_MPEG_VIDC_EXTRADATA_METADATA_MBI = 21,
	V4L2_MPEG_VIDC_EXTRADATA_VQZIP_SEI = 22,
#define V4L2_MPEG_VIDC_EXTRADATA_HDR10PLUS_METADATA \
	V4L2_MPEG_VIDC_EXTRADATA_HDR10PLUS_METADATA
	V4L2_MPEG_VIDC_EXTRADATA_HDR10PLUS_METADATA = 23,
	V4L2_MPEG_VIDC_EXTRADATA_ROI_QP = 24,
#define V4L2_MPEG_VIDC_EXTRADATA_OUTPUT_CROP \
	V4L2_MPEG_VIDC_EXTRADATA_OUTPUT_CROP
	V4L2_MPEG_VIDC_EXTRADATA_OUTPUT_CROP = 25,
#define V4L2_MPEG_VIDC_EXTRADATA_DISPLAY_COLOUR_SEI \
	V4L2_MPEG_VIDC_EXTRADATA_DISPLAY_COLOUR_SEI
	V4L2_MPEG_VIDC_EXTRADATA_DISPLAY_COLOUR_SEI = 26,
#define V4L2_MPEG_VIDC_EXTRADATA_CONTENT_LIGHT_LEVEL_SEI \
	V4L2_MPEG_VIDC_EXTRADATA_CONTENT_LIGHT_LEVEL_SEI
	V4L2_MPEG_VIDC_EXTRADATA_CONTENT_LIGHT_LEVEL_SEI = 27,
#define V4L2_MPEG_VIDC_EXTRADATA_PQ_INFO \
	V4L2_MPEG_VIDC_EXTRADATA_PQ_INFO
	V4L2_MPEG_VIDC_EXTRADATA_PQ_INFO = 28,
#define V4L2_MPEG_VIDC_EXTRADATA_VUI_DISPLAY \
	V4L2_MPEG_VIDC_EXTRADATA_VUI_DISPLAY
	V4L2_MPEG_VIDC_EXTRADATA_VUI_DISPLAY = 29,
#define V4L2_MPEG_VIDC_EXTRADATA_VPX_COLORSPACE \
	V4L2_MPEG_VIDC_EXTRADATA_VPX_COLORSPACE
	V4L2_MPEG_VIDC_EXTRADATA_VPX_COLORSPACE = 30,
#define V4L2_MPEG_VIDC_EXTRADATA_UBWC_CR_STATS_INFO \
	V4L2_MPEG_VIDC_EXTRADATA_UBWC_CR_STATS_INFO
	V4L2_MPEG_VIDC_EXTRADATA_UBWC_CR_STATS_INFO = 31,
#define V4L2_MPEG_VIDC_EXTRADATA_ENC_FRAME_QP \
	V4L2_MPEG_VIDC_EXTRADATA_ENC_FRAME_QP
	V4L2_MPEG_VIDC_EXTRADATA_ENC_FRAME_QP = 32,
	V4L2_MPEG_VIDC_EXTRADATA_VC1_SEQDISP = 33,
	V4L2_MPEG_VIDC_EXTRADATA_YUV_STATS = 34,
};

enum v4l2_mpeg_cvp_extradata {
	V4L2_MPEG_CVP_EXTRADATA_NONE = 0,
	V4L2_MPEG_CVP_EXTRADATA_INTERLACE_VIDEO = 2,
	V4L2_MPEG_CVP_EXTRADATA_TIMESTAMP = 5,
	V4L2_MPEG_CVP_EXTRADATA_S3D_FRAME_PACKING = 6,
	V4L2_MPEG_CVP_EXTRADATA_FRAME_RATE = 7,
	V4L2_MPEG_CVP_EXTRADATA_PANSCAN_WINDOW = 8,
	V4L2_MPEG_CVP_EXTRADATA_RECOVERY_POINT_SEI = 9,
	V4L2_MPEG_CVP_EXTRADATA_NUM_CONCEALED_MB = 11,
	V4L2_MPEG_CVP_EXTRADATA_ASPECT_RATIO = 15,
	V4L2_MPEG_CVP_EXTRADATA_MPEG2_SEQDISP = 16,
	V4L2_MPEG_CVP_EXTRADATA_STREAM_USERDATA = 17,
	V4L2_MPEG_CVP_EXTRADATA_FRAME_QP = 18,
	V4L2_MPEG_CVP_EXTRADATA_LTR = 20,
#define V4L2_MPEG_CVP_EXTRADATA_HDR10PLUS_METADATA \
	V4L2_MPEG_CVP_EXTRADATA_HDR10PLUS_METADATA
	V4L2_MPEG_CVP_EXTRADATA_HDR10PLUS_METADATA = 23,
	V4L2_MPEG_CVP_EXTRADATA_ROI_QP = 24,
	V4L2_MPEG_CVP_EXTRADATA_OUTPUT_CROP = 25,
	V4L2_MPEG_CVP_EXTRADATA_DISPLAY_COLOUR_SEI = 26,
	V4L2_MPEG_CVP_EXTRADATA_CONTENT_LIGHT_LEVEL_SEI = 27,
	V4L2_MPEG_CVP_EXTRADATA_VUI_DISPLAY = 29,
	V4L2_MPEG_CVP_EXTRADATA_VPX_COLORSPACE = 30,
	V4L2_MPEG_CVP_EXTRADATA_UBWC_CR_STATS_INFO = 31,
};

#define V4L2_CID_MPEG_VIDEO_MULTI_SLICE_DELIVERY_MODE   \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 18)

#define V4L2_CID_MPEG_VIDC_VIDEO_VUI_TIMING_INFO \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 19)

enum v4l2_mpeg_vidc_video_vui_timing_info {
	V4L2_MPEG_VIDC_VIDEO_VUI_TIMING_INFO_DISABLED = 0,
	V4L2_MPEG_VIDC_VIDEO_VUI_TIMING_INFO_ENABLED = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_VP8_PROFILE_LEVEL \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 20)
enum v4l2_mpeg_vidc_video_vp8_profile_level {
	V4L2_MPEG_VIDC_VIDEO_VP8_UNUSED,
	V4L2_MPEG_VIDC_VIDEO_VP8_VERSION_0,
	V4L2_MPEG_VIDC_VIDEO_VP8_VERSION_1,
	V4L2_MPEG_VIDC_VIDEO_VP8_VERSION_2,
	V4L2_MPEG_VIDC_VIDEO_VP8_VERSION_3,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_PRESERVE_TEXT_QUALITY \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 21)
enum v4l2_mpeg_vidc_video_preserve_text_quality {
	V4L2_MPEG_VIDC_VIDEO_PRESERVE_TEXT_QUALITY_DISABLED = 0,
	V4L2_MPEG_VIDC_VIDEO_PRESERVE_TEXT_QUALITY_ENABLED = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_STREAM_OUTPUT_MODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 22)
enum v4l2_mpeg_vidc_video_decoder_multi_stream {
	V4L2_CID_MPEG_VIDC_VIDEO_STREAM_OUTPUT_PRIMARY = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_STREAM_OUTPUT_SECONDARY = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_MPEG2_LEVEL	(V4L2_CID_MPEG_MSM_VIDC_BASE+23)
enum v4l2_mpeg_vidc_video_mpeg2_level {
	V4L2_MPEG_VIDC_VIDEO_MPEG2_LEVEL_0	= 0,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_LEVEL_1	= 1,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_LEVEL_2	= 2,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_LEVEL_3	= 3,
};
#define V4L2_CID_MPEG_VIDC_VIDEO_MPEG2_PROFILE	(V4L2_CID_MPEG_MSM_VIDC_BASE+24)
enum v4l2_mpeg_vidc_video_mpeg2_profile {
	V4L2_MPEG_VIDC_VIDEO_MPEG2_PROFILE_SIMPLE		= 0,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_PROFILE_MAIN			= 1,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_PROFILE_HIGH			= 2,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_PROFILE_SNR_SCALABLE		= 3,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_PROFILE_SPATIAL_SCALABLE	= 4,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_PROFILE_422			= 5,
};

enum v4l2_mpeg_vidc_video_mvc_layout {
	V4L2_MPEG_VIDC_VIDEO_MVC_SEQUENTIAL = 0,
	V4L2_MPEG_VIDC_VIDEO_MVC_TOP_BOTTOM = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_CONCEAL_COLOR \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 25)

#define V4L2_CID_MPEG_VIDC_VIDEO_LTRMODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 26)

enum v4l2_mpeg_vidc_video_ltrmode {
	V4L2_MPEG_VIDC_VIDEO_LTR_MODE_DISABLE = 0,
	V4L2_MPEG_VIDC_VIDEO_LTR_MODE_MANUAL = 1,
	V4L2_MPEG_VIDC_VIDEO_LTR_MODE_PERIODIC = 2
};

#define V4L2_CID_MPEG_VIDC_VIDEO_LTRCOUNT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 27)

#define V4L2_CID_MPEG_VIDC_VIDEO_USELTRFRAME \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 28)

#define V4L2_CID_MPEG_VIDC_VIDEO_MARKLTRFRAME \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 29)

#define V4L2_CID_MPEG_VIDC_VIDEO_HIER_P_NUM_LAYERS \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 30)

#define V4L2_CID_MPEG_VIDC_VIDEO_ALLOC_MODE_OUTPUT       \
		(V4L2_CID_MPEG_MSM_VIDC_BASE+31)
enum v4l2_mpeg_vidc_video_alloc_mode_type {
	V4L2_MPEG_VIDC_VIDEO_STATIC = 0,
	V4L2_MPEG_VIDC_VIDEO_RING = 1,
	V4L2_MPEG_VIDC_VIDEO_DYNAMIC = 2,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_IFRAME_X_RANGE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 32)

#define V4L2_CID_MPEG_VIDC_VIDEO_PFRAME_X_RANGE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 33)

#define V4L2_CID_MPEG_VIDC_VIDEO_BFRAME_X_RANGE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 34)

#define V4L2_CID_MPEG_VIDC_VIDEO_IFRAME_Y_RANGE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 35)

#define V4L2_CID_MPEG_VIDC_VIDEO_PFRAME_Y_RANGE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 36)

#define V4L2_CID_MPEG_VIDC_VIDEO_BFRAME_Y_RANGE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 37)

#define V4L2_CID_MPEG_VIDC_VIDEO_VPX_ERROR_RESILIENCE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 38)

#define V4L2_CID_MPEG_VIDC_VIDEO_BUFFER_SIZE_LIMIT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 39)

enum vl42_mpeg_vidc_video_vpx_error_resilience {
	V4L2_MPEG_VIDC_VIDEO_VPX_ERROR_RESILIENCE_DISABLED = 0,
	V4L2_MPEG_VIDC_VIDEO_VPX_ERROR_RESILIENCE_ENABLED = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_HEVC_PROFILE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 40)
enum v4l2_mpeg_video_hevc_profile_legacy {
	V4L2_MPEG_VIDC_VIDEO_HEVC_PROFILE_MAIN			= 0,
	V4L2_MPEG_VIDC_VIDEO_HEVC_PROFILE_MAIN10		= 1,
	V4L2_MPEG_VIDC_VIDEO_HEVC_PROFILE_MAIN_STILL_PIC	= 2,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_HEVC_TIER_LEVEL \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 41)
enum v4l2_mpeg_video_hevc_level_legacy {
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_1	= 0,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_1	= 1,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_2	= 2,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_2	= 3,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_2_1	= 4,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_2_1	= 5,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_3	= 6,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_3	= 7,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_3_1	= 8,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_3_1	= 9,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_4	= 10,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_4	= 11,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_4_1	= 12,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_4_1	= 13,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_5	= 14,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_5	= 15,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_5_1	= 16,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_5_1	= 17,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_5_2	= 18,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_5_2	= 19,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_6	= 20,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_6	= 21,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_6_1	= 22,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_6_1	= 23,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_6_2	= 24,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_6_2	= 25,
#define V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_UNKNOWN \
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_UNKNOWN
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_UNKNOWN = 26,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_HIER_B_NUM_LAYERS \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 42)

#define V4L2_CID_MPEG_VIDC_VIDEO_HYBRID_HIERP_MODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 43)

#define V4L2_CID_MPEG_VIDC_VIDEO_DPB_COLOR_FORMAT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 44)

enum v4l2_mpeg_vidc_video_dpb_color_format {
	V4L2_MPEG_VIDC_VIDEO_DPB_COLOR_FMT_NONE = 0,
	V4L2_MPEG_VIDC_VIDEO_DPB_COLOR_FMT_UBWC = 1,
	V4L2_MPEG_VIDC_VIDEO_DPB_COLOR_FMT_TP10_UBWC = 2
};

#define V4L2_CID_VIDC_QBUF_MODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 45)
enum v4l2_vidc_qbuf_mode {
	V4L2_VIDC_QBUF_STANDARD = 0,
	V4L2_VIDC_QBUF_BATCHED = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_MAX_HIERP_LAYERS \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 46)

#define V4L2_CID_MPEG_VIDC_VIDEO_BASELAYER_ID \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 47)

#define V4L2_CID_MPEG_VIDC_VENC_PARAM_SAR_WIDTH \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 48)

#define V4L2_CID_MPEG_VIDC_VENC_PARAM_SAR_HEIGHT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 49)

#define V4L2_CID_MPEG_VIDC_VIDEO_VQZIP_SEI	\
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 50)

enum v4l2_mpeg_vidc_video_vqzip_sei_enable {
	V4L2_CID_MPEG_VIDC_VIDEO_VQZIP_SEI_DISABLE	= 0,
	V4L2_CID_MPEG_VIDC_VIDEO_VQZIP_SEI_ENABLE	= 1
};

#define V4L2_CID_MPEG_VIDC_VENC_PARAM_LAYER_BITRATE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 51)

#define V4L2_CID_MPEG_VIDC_VIDEO_PRIORITY \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 52)

enum v4l2_mpeg_vidc_video_priority {
	V4L2_MPEG_VIDC_VIDEO_PRIORITY_REALTIME_ENABLE = 0,
	V4L2_MPEG_VIDC_VIDEO_PRIORITY_REALTIME_DISABLE = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_OPERATING_RATE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 53)

#define V4L2_CID_MPEG_VIDC_VIDEO_VENC_BITRATE_TYPE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 54)

enum v4l2_mpeg_vidc_video_venc_bitrate_type_enable {
	V4L2_CID_MPEG_VIDC_VIDEO_VENC_BITRATE_DISABLE	= 0,
	V4L2_CID_MPEG_VIDC_VIDEO_VENC_BITRATE_ENABLE	= 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_VPE_CSC \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 55)

enum v4l2_cid_mpeg_vidc_video_vpe_csc_type_enable {
	V4L2_CID_MPEG_VIDC_VIDEO_VPE_CSC_DISABLE  = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_VPE_CSC_ENABLE   = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_LOWLATENCY_MODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 56)

enum v4l2_mpeg_vidc_video_lowlatency_mode {
	V4L2_CID_MPEG_VIDC_VIDEO_LOWLATENCY_DISABLE     = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_LOWLATENCY_ENABLE      = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_BLUR_WIDTH \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 57)

#define V4L2_CID_MPEG_VIDC_VIDEO_BLUR_HEIGHT \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 58)

#define V4L2_CID_MPEG_VIDC_VIDEO_H264_TRANSFORM_8x8 \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 59)
enum v4l2_mpeg_vidc_video_h264_transform_8x8 {
	V4L2_MPEG_VIDC_VIDEO_H264_TRANSFORM_8x8_DISABLE = 0,
	V4L2_MPEG_VIDC_VIDEO_H264_TRANSFORM_8x8_ENABLE = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_COLOR_SPACE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 60)

#define V4L2_CID_MPEG_VIDC_VIDEO_FULL_RANGE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 61)

enum v4l2_cid_mpeg_vidc_video_full_range {
	V4L2_CID_MPEG_VIDC_VIDEO_FULL_RANGE_DISABLE = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_FULL_RANGE_ENABLE = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_TRANSFER_CHARS \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 62)

#define V4L2_CID_MPEG_VIDC_VIDEO_MATRIX_COEFFS \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 63)

#define V4L2_CID_MPEG_VIDC_VIDEO_IFRAME_SIZE_TYPE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 64)

#define V4L2_CID_MPEG_VIDC_VIDEO_LAYER_ID \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 65)

#define V4L2_CID_MPEG_VIDC_VIDEO_VP9_PROFILE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 66)
enum v4l2_mpeg_vidc_video_vp9_profile {
	V4L2_MPEG_VIDC_VIDEO_VP9_PROFILE_UNUSED = 0,
	V4L2_MPEG_VIDC_VIDEO_VP9_PROFILE_P0 = 1,
	V4L2_MPEG_VIDC_VIDEO_VP9_PROFILE_P2_10 = 2,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_VP9_LEVEL \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 67)
enum v4l2_mpeg_vidc_video_vp9_level {
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_UNUSED = 0,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_1 = 1,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_11 = 2,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_2 = 3,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_21 = 4,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_3 = 5,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_31 = 6,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_4 = 7,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_41 = 8,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_5 = 9,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_51 = 10,
#define V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_6 \
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_6
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_6 = 11,
#define V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_61 \
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_61
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_61 = 12,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_COLOR_SPACE_CAPS \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 68)
#define V4L2_CID_MPEG_VIDC_VIDEO_ROTATION_CAPS \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 69)

#define V4L2_CID_MPEG_VIDC_VIDEO_MB_ERROR_MAP_REPORTING \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 70)
#define V4L2_CID_MPEG_VIDC_VIDEO_CONTINUE_DATA_TRANSFER \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 71)

#define V4L2_CID_MPEG_VIDC_VIDEO_ALLOC_MODE_INPUT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 72)

#define V4L2_CID_MPEG_VIDC_VIDEO_FRAME_ASSEMBLY	\
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 73)
enum v4l2_mpeg_vidc_video_assembly {
	V4L2_MPEG_VIDC_FRAME_ASSEMBLY_DISABLE = 0,
	V4L2_MPEG_VIDC_FRAME_ASSEMBLY_ENABLE = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_H263_PROFILE\
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 74)
enum v4l2_mpeg_vidc_video_h263_profile {
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_BASELINE = 0,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_H320CODING	= 1,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_BACKWARDCOMPATIBLE = 2,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_ISWV2 = 3,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_ISWV3 = 4,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_HIGHCOMPRESSION = 5,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_INTERNET = 6,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_INTERLACE = 7,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_HIGHLATENCY = 8,
};

#define V4L2_CID_MPEG_VIDEO_MIN_QP_PACKED \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 96)
#define V4L2_CID_MPEG_VIDEO_MAX_QP_PACKED \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 97)
#define V4L2_CID_MPEG_VIDC_VIDEO_ADAPTIVE_B \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 98)
#define V4L2_CID_MPEG_VIDC_VIDEO_I_FRAME_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 99)
#define V4L2_CID_MPEG_VIDC_VIDEO_P_FRAME_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 100)
#define V4L2_CID_MPEG_VIDC_VIDEO_B_FRAME_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 101)
#define V4L2_CID_MPEG_VIDC_VIDEO_I_FRAME_QP_MIN \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 102)
#define V4L2_CID_MPEG_VIDC_VIDEO_P_FRAME_QP_MIN \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 103)
#define V4L2_CID_MPEG_VIDC_VIDEO_B_FRAME_QP_MIN \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 104)
#define V4L2_CID_MPEG_VIDC_VIDEO_I_FRAME_QP_MAX \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 105)
#define V4L2_CID_MPEG_VIDC_VIDEO_P_FRAME_QP_MAX \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 106)
#define V4L2_CID_MPEG_VIDC_VIDEO_B_FRAME_QP_MAX \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 107)
#define V4L2_CID_MPEG_VIDC_VIDEO_QP_MASK \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 108)

enum v4l2_mpeg_vidc_video_venc_iframesize_type {
	V4L2_CID_MPEG_VIDC_VIDEO_IFRAME_SIZE_DEFAULT,
	V4L2_CID_MPEG_VIDC_VIDEO_IFRAME_SIZE_MEDIUM,
	V4L2_CID_MPEG_VIDC_VIDEO_IFRAME_SIZE_HUGE,
	V4L2_CID_MPEG_VIDC_VIDEO_IFRAME_SIZE_UNLIMITED,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_CONCEAL_COLOR_8BIT	\
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 109)
#define V4L2_CID_MPEG_VIDC_VIDEO_CONCEAL_COLOR_10BIT \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 110)

#define V4L2_CID_MPEG_VIDC_VIDEO_TME_PROFILE  \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 111)

enum v4l2_mpeg_vidc_video_tme_profile {
	V4L2_MPEG_VIDC_VIDEO_TME_PROFILE_0 = 0,
	V4L2_MPEG_VIDC_VIDEO_TME_PROFILE_1 = 1,
	V4L2_MPEG_VIDC_VIDEO_TME_PROFILE_2 = 2,
	V4L2_MPEG_VIDC_VIDEO_TME_PROFILE_3 = 3,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_TME_LEVEL \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 112)

enum v4l2_mpeg_vidc_video_tme_level {
	V4L2_MPEG_VIDC_VIDEO_TME_LEVEL_INTEGER = 0,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_TME_PAYLOAD_VERSION  \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 113)

#define V4L2_CID_MPEG_VIDC_VIDEO_VPE_CSC_CUSTOM_MATRIX \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 114)

#define V4L2_CID_MPEG_VIDC_VIDEO_FLIP (V4L2_CID_MPEG_MSM_VIDC_BASE + 115)
enum v4l2_mpeg_vidc_video_flip {
	V4L2_CID_MPEG_VIDC_VIDEO_FLIP_NONE = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_FLIP_HORI = 1,
	V4L2_CID_MPEG_VIDC_VIDEO_FLIP_VERT = 2,
	V4L2_CID_MPEG_VIDC_VIDEO_FLIP_BOTH = 3,
};

/* HDR SEI INFO related control IDs and definitions*/
#define V4L2_MPEG_VIDC_VENC_HDR_INFO_ENABLED 1
#define V4L2_MPEG_VIDC_VENC_HDR_INFO_DISABLED 0

#define V4L2_CID_MPEG_VIDC_VENC_HDR_INFO \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 116)
#define V4L2_CID_MPEG_VIDC_VENC_RGB_PRIMARY_00 \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 117)
#define V4L2_CID_MPEG_VIDC_VENC_RGB_PRIMARY_01 \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 118)
#define V4L2_CID_MPEG_VIDC_VENC_RGB_PRIMARY_10 \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 119)
#define V4L2_CID_MPEG_VIDC_VENC_RGB_PRIMARY_11 \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 120)
#define V4L2_CID_MPEG_VIDC_VENC_RGB_PRIMARY_20 \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 121)
#define V4L2_CID_MPEG_VIDC_VENC_RGB_PRIMARY_21 \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 122)
#define V4L2_CID_MPEG_VIDC_VENC_WHITEPOINT_X \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 123)
#define V4L2_CID_MPEG_VIDC_VENC_WHITEPOINT_Y \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 124)
#define V4L2_CID_MPEG_VIDC_VENC_MAX_DISP_LUM \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 125)
#define V4L2_CID_MPEG_VIDC_VENC_MIN_DISP_LUM \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 126)
#define V4L2_CID_MPEG_VIDC_VENC_MAX_CLL \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 127)
#define V4L2_CID_MPEG_VIDC_VENC_MAX_FLL \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 128)
#define V4L2_CID_MPEG_VIDC_VIDEO_FRAME_QUALITY \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 129)
#define V4L2_CID_MPEG_VIDC_IMG_GRID_ENABLE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 130)
#define V4L2_CID_MPEG_VIDC_VENC_BITRATE_SAVINGS \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 131)
#define V4L2_CID_MPEG_VIDC_VIDEO_ROI_TYPE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 132)
enum v4l2_mpeg_vidc_video_roi_type {
	V4L2_CID_MPEG_VIDC_VIDEO_ROI_TYPE_NONE = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_ROI_TYPE_2BIT = 1,
	V4L2_CID_MPEG_VIDC_VIDEO_ROI_TYPE_2BYTE = 2,
};

#define V4L2_CID_MPEG_VIDC_SET_PERF_LEVEL \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 133)
enum v4l2_mpeg_vidc_perf_level {
	V4L2_CID_MPEG_VIDC_PERF_LEVEL_NOMINAL   = 0,
	V4L2_CID_MPEG_VIDC_PERF_LEVEL_PERFORMANCE       = 1,
	V4L2_CID_MPEG_VIDC_PERF_LEVEL_TURBO     = 2,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_AIR_MBS (V4L2_CID_MPEG_MSM_VIDC_BASE + 134)
#define V4L2_CID_MPEG_VIDC_VIDEO_AIR_REF (V4L2_CID_MPEG_MSM_VIDC_BASE + 135)
#define V4L2_CID_MPEG_VIDC_VIDEO_CIR_MBS (V4L2_CID_MPEG_MSM_VIDC_BASE + 136)

#define V4L2_CID_MPEG_VIDC_VIDEO_H264_VUI_TIMING_INFO \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 137)

#define V4L2_CID_MPEG_VIDEO_MULTI_SLICE_GOB \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 138)

#define V4L2_CID_MPEG_VIDC_VIDEO_H264_VUI_BITSTREAM_RESTRICT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 139)
enum v4l2_mpeg_vidc_video_h264_vui_bitstream_restrict {
	V4L2_MPEG_VIDC_VIDEO_H264_VUI_BITSTREAM_RESTRICT_DISABLED = 0,
	V4L2_MPEG_VIDC_VIDEO_H264_VUI_BITSTREAM_RESTRICT_ENABLED = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_DEINTERLACE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 140)
enum v4l2_mpeg_vidc_video_deinterlace {
	V4L2_CID_MPEG_VIDC_VIDEO_DEINTERLACE_DISABLED = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_DEINTERLACE_ENABLED = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_MPEG4_TIME_RESOLUTION \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 141)

#define V4L2_CID_MPEG_VIDC_VIDEO_REQUEST_SEQ_HEADER \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 142)

#define V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_TIMESTAMP_MODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 143)
enum v4l2_mpeg_vidc_video_rate_control_timestamp_mode {
	V4L2_MPEG_VIDC_VIDEO_RATE_CONTROL_TIMESTAMP_MODE_HONOR = 0,
	V4L2_MPEG_VIDC_VIDEO_RATE_CONTROL_TIMESTAMP_MODE_IGNORE = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_ENABLE_INITIAL_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 144)
enum vl42_mpeg_vidc_video_enable_initial_qp {
	V4L2_CID_MPEG_VIDC_VIDEO_ENABLE_INITIAL_QP_IFRAME = 0x1,
	V4L2_CID_MPEG_VIDC_VIDEO_ENABLE_INITIAL_QP_PFRAME = 0x2,
	V4L2_CID_MPEG_VIDC_VIDEO_ENABLE_INITIAL_QP_BFRAME = 0x4,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_INITIAL_I_FRAME_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 145)

#define V4L2_CID_MPEG_VIDC_VIDEO_INITIAL_P_FRAME_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 146)

#define V4L2_CID_MPEG_VIDC_VIDEO_INITIAL_B_FRAME_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 147)

#define V4L2_CID_MPEG_VIDC_VIDEO_H264_NAL_SVC \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 148)

#define V4L2_CID_MPEG_VIDC_VIDEO_PERF_MODE	 \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 149)
enum v4l2_mpeg_vidc_video_perf_mode {
	V4L2_MPEG_VIDC_VIDEO_PERF_MAX_QUALITY = 1,
	V4L2_MPEG_VIDC_VIDEO_PERF_POWER_SAVE = 2
};

#define V4L2_CID_MPEG_VIDC_VIDEO_MBI_STATISTICS_MODE	\
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 150)

#define V4L2_CID_MPEG_VIDC_VIDEO_CONFIG_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 151)

#define V4L2_CID_MPEG_VIDC_VIDEO_H264_PIC_ORDER_CNT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 152)

#define V4L2_CID_MPEG_VIDC_VIDEO_SCS_THRESHOLD \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 153)

#define V4L2_CID_MPEG_VIDC_VIDEO_MVC_BUFFER_LAYOUT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 154)


#define V4L2_CID_MPEG_VIDC_VIDEO_SECURE_SCALING_THRESHOLD \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 155)

#define V4L2_CID_MPEG_VIDC_VIDEO_NON_SECURE_OUTPUT2 \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 156)

#define V4L2_CID_MPEG_VIDC_VIDEO_VP8_MIN_QP (V4L2_CID_MPEG_MSM_VIDC_BASE + 157)
#define V4L2_CID_MPEG_VIDC_VIDEO_VP8_MAX_QP (V4L2_CID_MPEG_MSM_VIDC_BASE + 158)

#define V4L2_CID_MPEG_VIDC_VIDEO_H263_LEVEL (V4L2_CID_MPEG_MSM_VIDC_BASE + 159)
enum v4l2_mpeg_vidc_video_h263_level {
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_1_0 = 0,
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_2_0 = 1,
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_3_0 = 2,
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_4_0 = 3,
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_4_5 = 4,
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_5_0 = 5,
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_6_0 = 6,
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_7_0 = 7,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_POST_LOOP_DEBLOCKER_MODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 160)


#define V4L2_CID_MPEG_VIDC_VIDEO_DIVX_FORMAT (V4L2_CID_MPEG_MSM_VIDC_BASE+161)

enum v4l2_mpeg_vidc_video_divx_format_type {
		V4L2_MPEG_VIDC_VIDEO_DIVX_FORMAT_4 = 0,
		V4L2_MPEG_VIDC_VIDEO_DIVX_FORMAT_5 = 1,
		V4L2_MPEG_VIDC_VIDEO_DIVX_FORMAT_6 = 2,
};

#define V4L2_CID_MPEG_VIDC_IMG_GRID_DIMENSION \
	(V4L2_CID_MPEG_MSM_VIDC_BASE+163)

#define V4L2_CID_MPEG_VIDC_VIDEO_FRAME_QP \
	(V4L2_CID_MPEG_MSM_VIDC_BASE+164)

#define  \
V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_MODE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE+165)
enum v4l2_mpeg_vidc_video_intra_refresh_mode {
	V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_NONE = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_CYCLIC = 1,
	V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_RANDOMMODE = 2,
	V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_ADAPTIVE = 3,
	V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_CYCLIC_ADAPTIVE = 4,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_IR_MBS (V4L2_CID_MPEG_MSM_VIDC_BASE+166)

enum v4l2_mpeg_vidc_video_mbi_statistics_mode {
	V4L2_CID_MPEG_VIDC_VIDEO_MBI_MODE_DEFAULT = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_MBI_MODE_1 = 1,
	V4L2_CID_MPEG_VIDC_VIDEO_MBI_MODE_2 = 2,
	V4L2_CID_MPEG_VIDC_VIDEO_MBI_MODE_3 = 3,
};

enum vl42_mpeg_vidc_video_h264_svc_nal {
	V4L2_CID_MPEG_VIDC_VIDEO_H264_NAL_SVC_DISABLED = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_H264_NAL_SVC_ENABLED = 1,
};

enum v4l2_mpeg_vidc_video_h264_vui_timing_info {
	V4L2_MPEG_VIDC_VIDEO_H264_VUI_TIMING_INFO_DISABLED = 0,
	V4L2_MPEG_VIDC_VIDEO_H264_VUI_TIMING_INFO_ENABLED = 1
};
#define V4L2_CID_MPEG_VIDC_VENC_COMPLEXITY \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 167)

struct msm_vidc_extradata_header {
	unsigned int size;
	unsigned int:32; /** Keeping binary compatibility */
	unsigned int:32; /* with firmware and OpenMAX IL **/
	unsigned int type; /* msm_vidc_extradata_type */
	unsigned int data_size;
	unsigned char data[1];
};

struct msm_vidc_interlace_payload {
	unsigned int format;
	unsigned int color_format;
};

struct msm_vidc_framerate_payload {
	unsigned int frame_rate;
};

struct msm_vidc_ts_payload {
	unsigned int timestamp_lo;
	unsigned int timestamp_hi;
};

struct msm_vidc_concealmb_payload {
	unsigned int num_mbs;
};

struct msm_vidc_recoverysei_payload {
	unsigned int flags;
};

struct msm_vidc_aspect_ratio_payload {
	unsigned int size;
	unsigned int version;
	unsigned int port_index;
	unsigned int aspect_width;
	unsigned int aspect_height;
};

struct msm_vidc_mpeg2_seqdisp_payload {
	unsigned int video_format;
	unsigned int color_descp;
	unsigned int color_primaries;
	unsigned int transfer_char;
	unsigned int matrix_coeffs;
	unsigned int disp_width;
	unsigned int disp_height;
};

struct msm_vidc_input_crop_payload {
	unsigned int size;
	unsigned int version;
	unsigned int port_index;
	unsigned int left;
	unsigned int top;
	unsigned int width;
	unsigned int height;
};

#ifdef VENUS_USES_LEGACY_MISR_INFO
struct msm_vidc_misr_info {
	unsigned int misr_dpb_luma;
	unsigned int misr_dpb_chroma;
	unsigned int misr_opb_luma;
	unsigned int misr_opb_chroma;
};
#else
struct msm_vidc_misr_info {
	unsigned int misr_set;
	unsigned int misr_dpb_luma[8];
	unsigned int misr_dpb_chroma[8];
	unsigned int misr_opb_luma[8];
	unsigned int misr_opb_chroma[8];
};
#endif

struct msm_vidc_output_crop_payload {
	unsigned int size;
	unsigned int version;
	unsigned int port_index;
	unsigned int left;
	unsigned int top;
	unsigned int display_width;
	unsigned int display_height;
	unsigned int width;
	unsigned int height;
	unsigned int frame_num;
	unsigned int bit_depth_y;
	unsigned int bit_depth_c;
	struct msm_vidc_misr_info misr_info[2];
};

struct msm_vidc_extradata_index {
	unsigned int type;
	union {
		struct msm_vidc_input_crop_payload input_crop;
		struct msm_vidc_aspect_ratio_payload aspect_ratio;
	};
};

struct msm_vidc_panscan_window {
	unsigned int panscan_height_offset;
	unsigned int panscan_width_offset;
	unsigned int panscan_window_width;
	unsigned int panscan_window_height;
};

struct msm_vidc_panscan_window_payload {
	unsigned int num_panscan_windows;
	struct msm_vidc_panscan_window wnd[1];
};

struct msm_vidc_stream_userdata_payload {
	unsigned int type;
	unsigned int data[1];
};

struct msm_vidc_frame_qp_payload {
	unsigned int frame_qp;
	unsigned int qp_sum;
	unsigned int skip_qp_sum;
	unsigned int skip_num_blocks;
	unsigned int total_num_blocks;
};

struct msm_vidc_dts_payload {
	unsigned int timestamp_hi;
	unsigned int timestamp_lo;
};

struct msm_vidc_frame_bits_info_payload {
	unsigned int frame_bits;
	unsigned int header_bits;
};

struct msm_vidc_s3d_frame_packing_payload {
	unsigned int fpa_id;
	unsigned int cancel_flag;
	unsigned int fpa_type;
	unsigned int quin_cunx_flag;
	unsigned int content_interprtation_type;
	unsigned int spatial_flipping_flag;
	unsigned int frame0_flipped_flag;
	unsigned int field_views_flag;
	unsigned int current_frame_is_frame0_flag;
	unsigned int frame0_self_contained_flag;
	unsigned int frame1_self_contained_flag;
	unsigned int frame0_graid_pos_x;
	unsigned int frame0_graid_pos_y;
	unsigned int frame1_graid_pos_x;
	unsigned int frame1_graid_pos_y;
	unsigned int fpa_reserved_byte;
	unsigned int fpa_repetition_period;
	unsigned int fpa_extension_flag;
};

struct msm_vidc_ubwc_cr_stats_info {
	unsigned int stats_tile_32;
	unsigned int stats_tile_64;
	unsigned int stats_tile_96;
	unsigned int stats_tile_128;
	unsigned int stats_tile_160;
	unsigned int stats_tile_192;
	unsigned int stats_tile_256;
};

struct msm_vidc_yuv_stats_payload {
	unsigned int frame_qp;
	unsigned int texture;
	unsigned int luma_in_q16;
	unsigned int frame_difference;
};

struct msm_vidc_vpx_colorspace_payload {
	unsigned int color_space;
	unsigned int yuv_range_flag;
	unsigned int sumsampling_x;
	unsigned int sumsampling_y;
};

struct msm_vidc_roi_qp_payload {
	int upper_qp_offset;
	int lower_qp_offset;
	unsigned int b_roi_info;
	int mbi_info_size;
	unsigned int data[1];
};

#define MSM_VIDC_EXTRADATA_ROI_DELTAQP 0x1
struct msm_vidc_roi_deltaqp_payload {
	unsigned int b_roi_info; /*Enable/Disable*/
	int mbi_info_size; /*Size of QP data*/
	unsigned int data[1];
};

struct msm_vidc_hdr10plus_metadata_payload {
	unsigned int size;
	unsigned int data[1];
};

struct msm_vidc_mastering_display_colour_sei_payload {
	unsigned int nDisplayPrimariesX[3];
	unsigned int nDisplayPrimariesY[3];
	unsigned int nWhitePointX;
	unsigned int nWhitePointY;
	unsigned int nMaxDisplayMasteringLuminance;
	unsigned int nMinDisplayMasteringLuminance;
};

struct msm_vidc_content_light_level_sei_payload {
	unsigned int nMaxContentLight;
	unsigned int nMaxPicAverageLight;
};

struct msm_vidc_vui_display_info_payload {
	unsigned int video_signal_present_flag;
	unsigned int video_format;
	unsigned int bit_depth_y;
	unsigned int bit_depth_c;
	unsigned int video_full_range_flag;
	unsigned int color_description_present_flag;
	unsigned int color_primaries;
	unsigned int transfer_characteristics;
	unsigned int matrix_coefficients;
	unsigned int chroma_location_info_present_flag;
	unsigned int chroma_format_idc;
	unsigned int separate_color_plane_flag;
	unsigned int chroma_sample_loc_type_top_field;
	unsigned int chroma_sample_loc_type_bottom_field;
};

/* msm_vidc_extradata_type */
#define MSM_VIDC_EXTRADATA_NONE 0x00000000
#define MSM_VIDC_EXTRADATA_MB_QUANTIZATION 0x00000001
#define MSM_VIDC_EXTRADATA_INTERLACE_VIDEO 0x00000002
#define MSM_VIDC_EXTRADATA_TIMESTAMP 0x00000005
#define MSM_VIDC_EXTRADATA_S3D_FRAME_PACKING 0x00000006
#define MSM_VIDC_EXTRADATA_FRAME_RATE 0x00000007
#define MSM_VIDC_EXTRADATA_PANSCAN_WINDOW 0x00000008
#define MSM_VIDC_EXTRADATA_RECOVERY_POINT_SEI 0x00000009
#define MSM_VIDC_EXTRADATA_MPEG2_SEQDISP 0x0000000D
#define MSM_VIDC_EXTRADATA_STREAM_USERDATA 0x0000000E
#define MSM_VIDC_EXTRADATA_FRAME_QP 0x0000000F
#define MSM_VIDC_EXTRADATA_FRAME_BITS_INFO 0x00000010
#define MSM_VIDC_EXTRADATA_ROI_QP 0x00000013
#define MSM_VIDC_EXTRADATA_VPX_COLORSPACE_INFO 0x00000014
#define MSM_VIDC_EXTRADATA_MASTERING_DISPLAY_COLOUR_SEI 0x00000015
#define MSM_VIDC_EXTRADATA_CONTENT_LIGHT_LEVEL_SEI 0x00000016
#define MSM_VIDC_EXTRADATA_PQ_INFO 0x00000017
#define MSM_VIDC_EXTRADATA_COLOUR_REMAPPING_INFO_SEI 0x00000018
#define MSM_VIDC_EXTRADATA_UBWC_CR_STAT_INFO 0x00000019
#define MSM_VIDC_EXTRADATA_HDR10PLUS_METADATA 0x0000001A
#define MSM_VIDC_EXTRADATA_INPUT_CROP 0x0700000E
#define MSM_VIDC_EXTRADATA_OUTPUT_CROP 0x0700000F
#define MSM_VIDC_EXTRADATA_MULTISLICE_INFO 0x7F100000
#define MSM_VIDC_EXTRADATA_NUM_CONCEALED_MB 0x7F100001
#define MSM_VIDC_EXTRADATA_INDEX 0x7F100002
#define MSM_VIDC_EXTRADATA_ASPECT_RATIO 0x7F100003
#define MSM_VIDC_EXTRADATA_METADATA_LTR 0x7F100004
#define MSM_VIDC_EXTRADATA_METADATA_MBI 0x7F100005
#define MSM_VIDC_EXTRADATA_VUI_DISPLAY_INFO 0x7F100006
#define MSM_VIDC_EXTRADATA_ENC_DTS_INFO 0x7F100008

/* msm_vidc_interlace_type */
#define MSM_VIDC_INTERLACE_FRAME_PROGRESSIVE 0x01
#define MSM_VIDC_INTERLACE_INTERLEAVE_FRAME_TOPFIELDFIRST 0x02
#define MSM_VIDC_INTERLACE_INTERLEAVE_FRAME_BOTTOMFIELDFIRST 0x04
#define MSM_VIDC_INTERLACE_FRAME_TOPFIELDFIRST 0x08
#define MSM_VIDC_INTERLACE_FRAME_BOTTOMFIELDFIRST 0x10
#define MSM_VIDC_INTERLACE_FRAME_MBAFF 0x20

/* msm_vidc_framepack_type */
#define MSM_VIDC_FRAMEPACK_CHECKERBOARD 0x00
#define MSM_VIDC_FRAMEPACK_COLUMN_INTERLEAVE 0x01
#define MSM_VIDC_FRAMEPACK_ROW_INTERLEAVE 0x02
#define MSM_VIDC_FRAMEPACK_SIDE_BY_SIDE 0x03
#define MSM_VIDC_FRAMEPACK_TOP_BOTTOM 0x04
#define MSM_VIDC_FRAMEPACK_TEMPORAL_INTERLEAVE 0x05

/* msm_vidc_recovery_sei */
#define MSM_VIDC_FRAME_RECONSTRUCTION_INCORRECT 0x0
#define MSM_VIDC_FRAME_RECONSTRUCTION_CORRECT 0x01
#define MSM_VIDC_FRAME_RECONSTRUCTION_APPROXIMATELY_CORRECT 0x02

/* msm_vidc_userdata_type */
#define MSM_VIDC_USERDATA_TYPE_FRAME 0x1
#define MSM_VIDC_USERDATA_TYPE_TOP_FIELD 0x2
#define MSM_VIDC_USERDATA_TYPE_BOTTOM_FIELD 0x3

/* See colour_primaries of ISO/IEC 14496 for significance */
/* msm_vidc_h264_color_primaries_values */
#define MSM_VIDC_RESERVED_1 0
#define MSM_VIDC_BT709_5 1
#define MSM_VIDC_UNSPECIFIED 2
#define MSM_VIDC_RESERVED_2 3
#define MSM_VIDC_BT470_6_M 4
#define MSM_VIDC_BT601_6_625 5
#define MSM_VIDC_BT470_6_BG MSM_VIDC_BT601_6_625
#define MSM_VIDC_BT601_6_525 6
#define MSM_VIDC_SMPTE_240M 7
#define MSM_VIDC_GENERIC_FILM 8
#define MSM_VIDC_BT2020 9

/* msm_vidc_vp9_color_primaries_values */
#define MSM_VIDC_CS_UNKNOWN 0
#define MSM_VIDC_CS_BT_601 1
#define MSM_VIDC_CS_BT_709 2
#define MSM_VIDC_CS_SMPTE_170 3
#define MSM_VIDC_CS_SMPTE_240 4
#define MSM_VIDC_CS_BT_2020 5
#define MSM_VIDC_CS_RESERVED 6
#define MSM_VIDC_CS_RGB 7

/* msm_vidc_h264_matrix_coeff_values */
#define MSM_VIDC_MATRIX_RGB 0
#define MSM_VIDC_MATRIX_BT_709_5 1
#define MSM_VIDC_MATRIX_UNSPECIFIED 2
#define MSM_VIDC_MATRIX_RESERVED 3
#define MSM_VIDC_MATRIX_FCC_47 4
#define MSM_VIDC_MATRIX_601_6_625 5
#define MSM_VIDC_MATRIX_BT470_BG MSM_VIDC_MATRIX_601_6_625
#define MSM_VIDC_MATRIX_601_6_525 6
#define MSM_VIDC_MATRIX_SMPTE_170M MSM_VIDC_MATRIX_601_6_525
#define MSM_VIDC_MATRIX_SMPTE_240M 7
#define MSM_VIDC_MATRIX_Y_CG_CO 8
#define MSM_VIDC_MATRIX_BT_2020 9
#define MSM_VIDC_MATRIX_BT_2020_CONST 10

/* msm_vidc_h264_transfer_chars_values */
#define MSM_VIDC_TRANSFER_RESERVED_1 0
#define MSM_VIDC_TRANSFER_BT709_5 1
#define MSM_VIDC_TRANSFER_UNSPECIFIED 2
#define MSM_VIDC_TRANSFER_RESERVED_2 3
#define MSM_VIDC_TRANSFER_BT_470_6_M 4
#define MSM_VIDC_TRANSFER_BT_470_6_BG 5
#define MSM_VIDC_TRANSFER_601_6_625 6
#define MSM_VIDC_TRANSFER_601_6_525 MSM_VIDC_TRANSFER_601_6_625
#define MSM_VIDC_TRANSFER_SMPTE_240M 7
#define MSM_VIDC_TRANSFER_LINEAR 8
#define MSM_VIDC_TRANSFER_LOG_100_1 9
#define MSM_VIDC_TRANSFER_LOG_100_SQRT10_1 10
#define MSM_VIDC_TRANSFER_IEC_61966 11
#define MSM_VIDC_TRANSFER_BT_1361 12
#define MSM_VIDC_TRANSFER_SRGB 13
#define MSM_VIDC_TRANSFER_BT_2020_10 14
#define MSM_VIDC_TRANSFER_BT_2020_12 15
#define MSM_VIDC_TRANSFER_SMPTE_ST2084 16
#define MSM_VIDC_TRANSFER_SMPTE_ST428_1 17
#define MSM_VIDC_TRANSFER_HLG 18

/* msm_vidc_pixel_depth */
#define MSM_VIDC_BIT_DEPTH_8 0
#define MSM_VIDC_BIT_DEPTH_10 1
#define MSM_VIDC_BIT_DEPTH_UNSUPPORTED 0XFFFFFFFF

/* msm_vidc_video_format */
#define MSM_VIDC_COMPONENT 0
#define MSM_VIDC_PAL 1
#define MSM_VIDC_NTSC 2
#define MSM_VIDC_SECAM 3
#define MSM_VIDC_MAC 4
#define MSM_VIDC_UNSPECIFIED_FORMAT 5
#define MSM_VIDC_RESERVED_1_FORMAT 6
#define MSM_VIDC_RESERVED_2_FORMAT 7

/* msm_vidc_color_desc_flag */
#define MSM_VIDC_COLOR_DESC_NOT_PRESENT 0
#define MSM_VIDC_COLOR_DESC_PRESENT 1

/*  msm_vidc_pic_struct */
#define MSM_VIDC_PIC_STRUCT_MAYBE_INTERLACED 0x0
#define MSM_VIDC_PIC_STRUCT_PROGRESSIVE 0x1

/*default when layer ID isn't specified*/
#define MSM_VIDC_ALL_LAYER_ID 0xFF

#endif
