/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Qualcomm SDM845 interconnect IDs
 *
 * Copyright (c) 2018, Linaro Ltd.
 * Copyright (c) 2025, Pavel Dubrova <pashadubrova@gmail.com>
 *
 * Author: Georgi Djakov <georgi.djakov@linaro.org>
 */

#ifndef __DT_BINDINGS_INTERCONNECT_QCOM_SDM845_H
#define __DT_BINDINGS_INTERCONNECT_QCOM_SDM845_H

#define MASTER_A1NOC_CFG		0
#define MASTER_BLSP_1			1
#define MASTER_TSIF			2
#define MASTER_SDCC_2			3
#define MASTER_SDCC_4			4
#define MASTER_UFS_CARD			5
#define MASTER_UFS_MEM			6
#define MASTER_PCIE_0			7
#define MASTER_A2NOC_CFG		8
#define MASTER_QDSS_BAM			9
#define MASTER_BLSP_2			10
#define MASTER_CNOC_A2NOC		11
#define MASTER_CRYPTO_CORE_0		12
#define MASTER_IPA			13
#define MASTER_PCIE_1			14
#define MASTER_QDSS_ETR			15
#define MASTER_USB3_0			16
#define MASTER_USB3_1			17
#define MASTER_CAMNOC_HF0_UNCOMP	18
#define MASTER_CAMNOC_HF1_UNCOMP	19
#define MASTER_CAMNOC_SF_UNCOMP		20
#define MASTER_SPDM			21
#define MASTER_SNOC_CNOC		22
#define MASTER_CNOC_DC_NOC		23
#define MASTER_AMPSS_M0			24
#define MASTER_GNOC_CFG			25
#define MASTER_IPA_CORE			26
#define MASTER_LLCC			27
#define MASTER_TCU_0			28
#define MASTER_MEM_NOC_CFG		29
#define MASTER_GNOC_MEM_NOC		30
#define MASTER_MNOC_HF_MEM_NOC		31
#define MASTER_MNOC_SF_MEM_NOC		32
#define MASTER_SNOC_GC_MEM_NOC		33
#define MASTER_SNOC_SF_MEM_NOC		34
#define MASTER_GRAPHICS_3D		35
#define MASTER_CNOC_MNOC_CFG		36
#define MASTER_CAMNOC_HF0		37
#define MASTER_CAMNOC_HF1		38
#define MASTER_CAMNOC_SF		39
#define MASTER_MDP_PORT0		40
#define MASTER_MDP_PORT1		41
#define MASTER_ROTATOR			42
#define MASTER_VIDEO_P0			43
#define MASTER_VIDEO_P1			44
#define MASTER_VIDEO_PROC		45
#define MASTER_SNOC_CFG			46
#define MASTER_A1NOC_SNOC		47
#define MASTER_A2NOC_SNOC		48
#define MASTER_GNOC_SNOC		49
#define MASTER_MEM_NOC_SNOC		50
#define MASTER_ANOC_PCIE_SNOC		51
#define MASTER_PIMEM			52
#define MASTER_GIC			53
#define MASTER_ALC			54

#define SLAVE_A1NOC_SNOC		512
#define SLAVE_SERVICE_A1NOC		513
#define SLAVE_ANOC_PCIE_A1NOC_SNOC	514
#define SLAVE_A2NOC_SNOC		515
#define SLAVE_ANOC_PCIE_SNOC		516
#define SLAVE_SERVICE_A2NOC		517
#define SLAVE_CAMNOC_UNCOMP		518
#define SLAVE_A1NOC_CFG			519
#define SLAVE_A2NOC_CFG			520
#define SLAVE_AOP			521
#define SLAVE_AOSS			522
#define SLAVE_CAMERA_CFG		523
#define SLAVE_CLK_CTL			524
#define SLAVE_CDSP_CFG			525
#define SLAVE_RBCPR_CX_CFG		526
#define SLAVE_CRYPTO_0_CFG		527
#define SLAVE_DCC_CFG			528
#define SLAVE_CNOC_DDRSS		529
#define SLAVE_DISPLAY_CFG		530
#define SLAVE_GLM			531
#define SLAVE_GRAPHICS_3D_CFG		532
#define SLAVE_IMEM_CFG			533
#define SLAVE_IPA_CFG			534
#define SLAVE_CNOC_MNOC_CFG		535
#define SLAVE_PCIE_0_CFG		536
#define SLAVE_PCIE_1_CFG		537
#define SLAVE_PDM			538
#define SLAVE_SOUTH_PHY_CFG		539
#define SLAVE_PIMEM_CFG			540
#define SLAVE_PRNG			541
#define SLAVE_QDSS_CFG			542
#define SLAVE_BLSP_2			543
#define SLAVE_BLSP_1			544
#define SLAVE_SDCC_2			545
#define SLAVE_SDCC_4			546
#define SLAVE_SNOC_CFG			547
#define SLAVE_SPDM_WRAPPER		548
#define SLAVE_SPSS_CFG			549
#define SLAVE_TCSR			550
#define SLAVE_TLMM_NORTH		551
#define SLAVE_TLMM_SOUTH		552
#define SLAVE_TSIF			553
#define SLAVE_UFS_CARD_CFG		554
#define SLAVE_UFS_MEM_CFG		555
#define SLAVE_USB3_0			556
#define SLAVE_USB3_1			557
#define SLAVE_VENUS_CFG			558
#define SLAVE_VSENSE_CTRL_CFG		559
#define SLAVE_CNOC_A2NOC		560
#define SLAVE_SERVICE_CNOC		561
#define SLAVE_LLCC_CFG			562
#define SLAVE_MEM_NOC_CFG		563
#define SLAVE_GNOC_SNOC			564
#define SLAVE_GNOC_MEM_NOC		565
#define SLAVE_SERVICE_GNOC		566
#define SLAVE_IPA_CORE			567
#define SLAVE_EBI1			568
#define SLAVE_MSS_PROC_MS_MPU_CFG	569
#define SLAVE_MEM_NOC_GNOC		570
#define SLAVE_LLCC			571
#define SLAVE_MEM_NOC_SNOC		572
#define SLAVE_SERVICE_MEM_NOC		573
#define SLAVE_MNOC_SF_MEM_NOC		574
#define SLAVE_MNOC_HF_MEM_NOC		575
#define SLAVE_SERVICE_MNOC		576
#define SLAVE_APPSS			577
#define SLAVE_SNOC_CNOC			578
#define SLAVE_SNOC_MEM_NOC_GC		579
#define SLAVE_SNOC_MEM_NOC_SF		580
#define SLAVE_OCIMEM			581
#define SLAVE_PCIE_0			582
#define SLAVE_PCIE_1			583
#define SLAVE_PIMEM			584
#define SLAVE_SERVICE_SNOC		585
#define SLAVE_QDSS_STM			586
#define SLAVE_TCU			587

#define MASTER_LLCC_DISP		1001
#define MASTER_MNOC_HF_MEM_NOC_DISP	1002
#define MASTER_MNOC_SF_MEM_NOC_DISP	1003
#define MASTER_MDP_PORT0_DISP		1004
#define MASTER_MDP_PORT1_DISP		1005
#define MASTER_ROTATOR_DISP		1006
#define SLAVE_EBI1_DISP			1512
#define SLAVE_LLCC_DISP			1513
#define SLAVE_MNOC_SF_MEM_NOC_DISP	1514
#define SLAVE_MNOC_HF_MEM_NOC_DISP	1515

#endif
